### ISSUE TITLE
make better error message if external atom is used with wrong input arity

### ISSUE THREAD

**Issue by peschue** [hexhex/hexlite#10]
Currently this causes (at least for type G external atoms):

```
  File "hexlite/clingobackend.py", line 794, in execute
    cc.ground([('base',())], ccc)
RuntimeError: <block>:1:2804-2825: error: error in context:
  Traceback (most recent call last):
    File "hexlite/clingobackend.py", line 402, in __call__
    outKnownTrue, outUnknown = self.eaeval.evaluate(self.holder, arguments, [])
    File "hexlite/clingobackend.py", line 393, in evaluate
    return self.evaluateCached(holder, inputtuple, predicateinputatoms)
    File "hexlite/clingobackend.py", line 385, in evaluateCached
    self, holder, inputtuple, predicateinputatoms)
    File "hexlite/clingobackend.py", line 245, in evaluate
    arg = self.clingo2hex(inputtuple[spec_idx])
  IndexError: tuple index out of range
```

**Comment by peschue** [comment]
fixed in https://github.com/hexhex/hexlite/commit/daf542010dce78e1138803f3bc8ca8d0f7011fa2
